(() => {
  'use strict';
  const Storage = window.KedrixOneStorage;
  const Data = window.KedrixOneData;
  const Utils = window.KedrixOneUtils;
  const Modules = window.KedrixOneModules;
  const Licensing = window.KedrixOneLicensing;
  const Templates = window.KedrixOneTemplates;
  const state = Storage.load(() => Data.initialState());
  const main = document.getElementById('mainContent');
  const title = document.getElementById('pageTitle');
  const toastRegion = document.getElementById('toastRegion');
  const sidebarNav = document.getElementById('sidebarNav');
  function save() { Storage.save(state); }
  function toast(text) { const el = document.createElement('div'); el.className = 'toast'; el.textContent = text; toastRegion.appendChild(el); setTimeout(() => el.remove(), 2500); }
  function filteredPractices() { const query = Utils.normalize(state.filterText); return state.practices.filter((p) => { const okStatus = state.statusFilter === 'Tutti' || p.status === state.statusFilter; const okQuery = !query || [p.reference, p.client, p.port, p.id].some((v) => Utils.normalize(v).includes(query)); return okStatus && okQuery; }); }
  function selectedPractice() { return state.practices.find((p) => p.id === state.selectedPracticeId) || null; }
  function currentRoute() { return Modules.normalizeRoute(state.currentRoute); }
  function currentRouteMeta() { return Modules.getRouteMeta(currentRoute()); }
  function expandedModules() { return Array.isArray(state.expandedModules) ? [...state.expandedModules] : []; }
  function ensureCurrentModuleExpanded() { const moduleKey = Modules.getModuleKeyFromRoute(currentRoute()); if (!moduleKey) return; const current = new Set(Array.isArray(state.expandedModules) ? state.expandedModules : []); if (!current.has(moduleKey)) { current.add(moduleKey); state.expandedModules = Array.from(current); } }
  function syncHash(replace = false) { const target = `#/${currentRoute()}`; if (window.location.hash === target) return; if (replace) window.history.replaceState(null, '', target); else window.location.hash = target; }
  function safeRoute(route) { const normalized = Modules.normalizeRoute(route); return Licensing.routeAllowed(normalized, Modules, state) ? normalized : 'dashboard'; }
  function navigate(route, options = {}) { const normalized = safeRoute(route); const changed = normalized !== state.currentRoute; state.currentRoute = normalized; ensureCurrentModuleExpanded(); save(); render(); if (options.syncHash !== false) syncHash(Boolean(options.replaceHash)); if (changed) { main.focus({ preventScroll: true }); window.scrollTo({ top: 0, behavior: 'smooth' }); } }
  function toggleModule(moduleKey) { const current = new Set(Array.isArray(state.expandedModules) ? state.expandedModules : []); if (current.has(moduleKey)) current.delete(moduleKey); else current.add(moduleKey); state.expandedModules = Array.from(current); save(); renderSidebar(); }
  function bindPracticeEvents() { const form = document.getElementById('practiceForm'); const filter = document.getElementById('filterText'); const status = document.getElementById('statusFilter'); filter?.addEventListener('input', (e) => { state.filterText = e.target.value || ''; save(); render(); }); status?.addEventListener('change', (e) => { state.statusFilter = e.target.value || 'Tutti'; save(); render(); }); form?.addEventListener('submit', (e) => { e.preventDefault(); const fd = new FormData(form); const p = { id: Utils.nextPracticeId(state.practices), reference: String(fd.get('reference') || '').trim(), client: String(fd.get('client') || '').trim(), type: String(fd.get('type') || '').trim(), port: String(fd.get('port') || '').trim(), eta: String(fd.get('eta') || '').trim(), priority: String(fd.get('priority') || '').trim(), status: String(fd.get('status') || '').trim(), notes: String(fd.get('notes') || '').trim() }; if (!p.reference || !p.client || !p.port || !p.eta) { toast('Compila i campi obbligatori.'); return; } state.practices.unshift(p); state.selectedPracticeId = p.id; state.operatorLogs.unshift({ id: Utils.nextLogId(state.operatorLogs), when: Utils.nowStamp(), practiceId: p.id, text: `Creata pratica ${p.reference}.` }); save(); render(); toast('Pratica salvata'); }); main.querySelectorAll('tbody tr[data-practice-id]').forEach((row) => { row.addEventListener('click', () => { state.selectedPracticeId = row.dataset.practiceId; save(); render(); }); }); }
  function bindSettingsEvents() { const plan = document.getElementById('companyPlan'); const activeUser = document.getElementById('activeUserId'); plan?.addEventListener('change', (e) => { Licensing.setCompanyPlan(state, e.target.value); save(); render(); toast(`Piano azienda impostato su ${String(e.target.value).toUpperCase()}`); }); activeUser?.addEventListener('change', (e) => { Licensing.setActiveUser(state, e.target.value); save(); render(); toast('Utente attivo aggiornato'); }); main.querySelectorAll('[data-toggle-company-module]').forEach((button) => { button.addEventListener('click', () => { Licensing.toggleCompanyModule(state, button.dataset.toggleCompanyModule); state.currentRoute = safeRoute(currentRoute()); save(); render(); toast('Acquisti azienda aggiornati'); }); }); main.querySelectorAll('[data-toggle-user-module]').forEach((button) => { button.addEventListener('click', () => { Licensing.toggleUserModule(state, button.dataset.toggleUserModule); state.currentRoute = safeRoute(currentRoute()); save(); render(); toast('Permessi utente aggiornati'); }); }); }
  function renderSidebar() { sidebarNav.innerHTML = Templates.sidebar(Licensing.visibleModules(Modules.list(), state), currentRoute(), expandedModules()); }
  function renderMain() { const route = currentRoute(); const routeMeta = currentRouteMeta(); const module = Modules.getModule(routeMeta.moduleKey); title.textContent = routeMeta.fullTitle; if (route === 'dashboard') { const visible = Licensing.visibleModules(Modules.list(), state); main.innerHTML = Templates.dashboard(state, Modules.summary(), { visibleModules: visible.length, companyPurchased: (state.companyConfig.purchasedModules || []).length }); return; } if (route === 'practices' || route === 'practices/elenco-pratiche') { main.innerHTML = Templates.practices(state, selectedPractice(), filteredPractices()); bindPracticeEvents(); return; } if (route === 'master-data') { main.innerHTML = Templates.contacts(state, module); return; } if (route === 'settings') { main.innerHTML = Templates.settings(state, Modules.list(), Licensing.getActiveUser(state)); bindSettingsEvents(); return; } if (routeMeta.type === 'module') { main.innerHTML = Templates.moduleOverview(module, state); return; } main.innerHTML = Templates.submodulePlaceholder(module, routeMeta); }
  function render() { renderSidebar(); renderMain(); }
  document.addEventListener('click', (event) => { const nav = event.target.closest('[data-route]'); if (nav) { navigate(nav.dataset.route); return; } const routeAction = event.target.closest('[data-route-action]'); if (routeAction) { navigate(routeAction.dataset.routeAction); return; } const toggle = event.target.closest('[data-module-toggle]'); if (toggle) { toggleModule(toggle.dataset.moduleToggle); return; } const action = event.target.closest('[data-action]'); if (!action) return; if (action.dataset.action === 'save-backup') { save(); toast('Backup locale aggiornato'); } if (action.dataset.action === 'reset-demo') { const fresh = Data.initialState(); Object.assign(state, fresh, { currentRoute: safeRoute(currentRoute()) }); save(); render(); toast('Dati demo ripristinati'); } });
  window.addEventListener('hashchange', () => { const routeFromHash = safeRoute(window.location.hash || state.currentRoute); if (routeFromHash === currentRoute()) return; state.currentRoute = routeFromHash; ensureCurrentModuleExpanded(); save(); render(); });
  state.currentRoute = safeRoute(window.location.hash || state.currentRoute); ensureCurrentModuleExpanded(); save(); render(); syncHash(true);
})();